### ISSUE TITLE
-S and -t incompatible

### ISSUE THREAD

**Issue by za3k** [clockfort/GitHub-Backup#16]
This is pretty obvious if you think about it but it would be good to catch when parsing options.

**Comment by Enrico204** [comment]
Not really: Token is for GitHub API access (which is always in HTTPS), "-S" is for SSH access for cloning (otherwise is made by using HTTPS). So options are not incompatibles.

**Comment by stv0g** [comment]
Fixed by #30

@clockfort can you close this issue?
