### ISSUE TITLE
License of github-backup.py?

### ISSUE THREAD

**Issue by hartwork** [clockfort/GitHub-Backup#19]
Hi!
`github-backup.py` does not seem to have a licensing header. What is it's license?
Best, Sebastian

**Comment by 1c7** [comment]
no one comment on this... so sad.. 
just use it whatever you like, seem author doesn't care about this at all.
there a issue post in 2014, two years ago and no one comment anything.

**Comment by hartwork** [comment]
@clockfort, any news?
