### ISSUE TITLE
Script no longer supports anonymous github access.

### ISSUE THREAD

**Issue by agargiulo** [clockfort/GitHub-Backup#21]
When I was last using this, you could just run the script without auth-ing to Github, which is fine if you don't want private repos. Now it forces you to authenticate. I can probably fix this, unless you don't think it's worth it.

**Comment by stv0g** [comment]
Anonymous API access is still possible and supported.

We just need to adjust the script a bit:

Replacing `gh.get_user()` with `gh.get_user(login)` should do it. But we need to figure out a way dot distinguish between the anonymous mode and authenticated mode. Maybe via a command line option?
