### ISSUE TITLE
Getting pygithub3.exceptions.NotFound: 404 - Not Found when using -t option

### ISSUE THREAD

**Issue by chachra** [clockfort/GitHub-Backup#26]
pygithub3.exceptions.NotFound: 404 - Not Found

**Comment by stv0g** [comment]
Fixed by #30 

The `-t` option has been removed. We now can only login via token or username (as the API permits).
We also migrated to `PyGitHub` package. So the issue is no longer relevant

@clockfort can you close this issue?
