### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/user/repos?per_page=100&type=all&page=1

### ISSUE THREAD

**Issue by inManage** [clockfort/GitHub-Backup#29]
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/user/repos?per_page=100&type=all&page=1

* it happens when trying to backup all repos with a python script ..

**Comment by gkoberger** [comment]
You now need to include `--token=??`

First, go to https://github.com/settings/tokens and generate a new token

Next, run the command with `--token=TOKEN_YOU_GENERATED`
