### ISSUE TITLE
Skip fork repositories

### ISSUE THREAD

**Issue by xuhdev** [clockfort/GitHub-Backup#3]
This is a really great script! But could you add support to skip fork repositories? I think many developers would not be interested in backup those repositories.

Thanks!

**Comment by Enrico204** [comment]
#25

**Comment by stv0g** [comment]
This is implemented. Please close issue

**Comment by xuhdev** [comment]
Could you give me a reference to the fix?

**Comment by stv0g** [comment]
2674a8f8fac7dc9598fb89cf6b51283337d96b7c

**Comment by xuhdev** [comment]
Thanks!
