### ISSUE TITLE
AttributeError: 'Github' object has no attribute 'get_org'

### ISSUE THREAD

**Issue by zen** [clockfort/GitHub-Backup#37]
When invoked as:
./github-backup.py token_or_password ~./github_backup -o org_name

I'm getting

Traceback (most recent call last):
  File "./github-backup.py", line 156, in <module>
    main()
  File "./github-backup.py", line 56, in main
    org = gh.get_org(args.org)
AttributeError: 'Github' object has no attribute 'get_org'

**Comment by mwenell** [comment]
I have the same problem when using -o option and organization neame. Any idea how to fix it?

**Comment by mlg-mentch** [comment]
Getting the same error here as well.

**Comment by victorkane** [comment]
Getting same error. Everything worked well for user. But when I added `-o orgname`, got the above error

**Comment by brian-oster-acme** [comment]
I am getting the same error as well.

**Comment by stv0g** [comment]
fixed by #34
