### ISSUE TITLE
Got Error 404 Not Found users#get-a-user if backup with GitHub token

### ISSUE THREAD

**Issue by tanshuai** [clockfort/GitHub-Backup#46]
```shell
% github-backup ghp_***mytoken*** github-backups/
```

github.GithubException.UnknownObjectException: 404 {"documentation_url": "https://docs.github.com/rest/reference/users#get-a-user", "message": "Not Found"}

**Comment by TheTechRobo** [comment]
IIRC, you need to use the `username` option. `--username (user)`
