### ISSUE TITLE
Unknown option -C (git)

### ISSUE THREAD

**Issue by tanmaymittal** [clockfort/GitHub-Backup#51]
Trying to back up my organizations repos
Command: `github-backup Leeps-Lab /home/leeps/backup/ -o Leeps-Lab -A`
All this does is copies the repo names and I get this in the terminal: 
```
INFO:github-backup:Repo doesn't exist, lets clone it
['git', '-C', '/home/leeps/backup/repositories/documentation', 'clone', 'https://github.com/Leeps-Lab/documentation.git', 'repository']
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```
I got this error for all the repos

**Comment by stv0g** [comment]
I think `-C` is just a short form of `--git-dir`. Maybe we should always use the long form here..

**Comment by tanmaymittal** [comment]
> I think `-C` is just a short form of `--git-dir`. Maybe we should always use the long form here..

@stv0g Should I change my cli arguments? 
Could the issue be because of my OS? I believe I am using CentOS.

**Comment by rolivella** [comment]
Same problem here! :(
